#!/bin/sh
set -e

if [ "$1" = remove ] && command -v systemctl >/dev/null 2>&1; then
    systemctl stop torkittend.service torkitten-caddy.service torkitten-tor.service || true
    systemctl disable torkittend.service >/dev/null || true
fi
if [ "$1" = remove ] && command -v apparmor_parser >/dev/null 2>&1; then
    apparmor_parser -R /etc/apparmor.d/torkitten >/dev/null 2>&1 || true
fi

exit 0
