[package]
name = "torkittend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64.workspace = true
getrandom.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
torkitten-auth = { path = "../torkitten-auth" }
torkitten-core = { path = "../torkitten-core" }
torkitten-proxy = { path = "../torkitten-proxy" }
torkitten-tor = { path = "../torkitten-tor" }
torkitten-vault = { path = "../torkitten-vault" }
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
