[package]
name = "torkitten-proxy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
getrandom.workspace = true
serde_json.workspace = true
thiserror.workspace = true
torkitten-core = { path = "../torkitten-core" }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
